# Generated by Django 2.1.11 on 2019-11-19 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0002_note_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
